# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('offers', models.CharField(max_length=200)),
                ('facilities', models.CharField(max_length=300)),
                ('spa', models.BooleanField(default=False)),
                ('trx', models.BooleanField(default=False)),
                ('crossfit', models.BooleanField(default=False)),
                ('yoga', models.BooleanField(default=False)),
                ('pilates', models.BooleanField(default=False)),
                ('zumba', models.BooleanField(default=False)),
                ('women_only', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
            ],
        ),
    ]
