# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='price_3months',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='price_6months',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='price_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='price_year',
            field=models.FloatField(default=0),
        ),
    ]
